// The calendar's words: the month grid, its day card and the plans. A chunk of
// its own with the calendar, so the first screen never carries them.
import { defineCopy } from '../../i18n'

export const copy = defineCopy('calendar', {
  label: 'Calendar',
  prev: 'Previous month',
  next: 'Next month',
  expected: (n: string) => `~${n} expected`,
  usual: (n: string) => `usual ${n}`,
  vsUsual: (pct: string, weekday: string) => `${pct} vs a usual ${weekday}`,
  dayLabel: (day: string, visitors: string) => `${day}: ${visitors} visitors`,
  dayLabelLater: (day: string, n: string) => `${day}: about ${n} expected`,
  weekdayAvg: (name: string, n: string) => `${name}: ${n} on average`,
  planFor: (day: string) => `A plan for ${day}`,
  planHint: 'What is planned',
  planSave: 'Save',
  planRemove: 'Remove plan',
  openDay: 'Open this day',
  close: 'Close',
  source: 'Source',
  page: 'Page',
  sales: (n: number) => (n === 1 ? '1 sale' : `${n} sales`),
  byHour: 'Visitors by the hour',
  hour: (hour: string, n: string) => `${hour}: ${n}`,
  empty: 'No visits this month',
  failed: "Couldn't load this month",
  wholeSite: 'Moments, notes and plans show the whole site',
  kind: {
    spike: 'Spike',
    surge: 'Surge',
    sale: 'Sale',
    milestone: 'Milestone',
    new_referrer: 'New referrer',
    ai: 'AI',
  },
  spike: (visitors: string, times: string) => `${visitors} visitors, ${times} the usual`,
  spikeNew: (visitors: string) => `${visitors} visitors, new traffic`,
  surge: (visitors: string, times: string) => `${visitors} in an hour, ${times} the usual`,
  sale: (n: number, amount: string) => (n === 1 ? `1 sale, ${amount}` : `${n} sales, ${amount}`),
  milestone: (step: string) => `Milestone ${step}`,
  newReferrer: (name: string) => `${name} sent its first visitors`,
  ai: (bot: string) => `First visit from ${bot}`,
})
