// Data's Story view: every sentence it can say, with the numbers it is built
// from handed in. What moves to the message files when translations come.
import { defineCopy } from '../../i18n'
import { bar } from './barCopy'

export const copy = defineCopy('storyview', {
  eyebrow: (period: string) => `${period}, in one line`,
  // The headline: a lead, the figure set apart, then the rest.
  newLead: 'Your story starts here. ',
  newRest: ' so far.',
  quietLead: 'A quiet stretch. ',
  quietRest: (before: string) => ` came, about the same as before (${before}).`,
  came: ' came',
  grewBy: (pct: string) => `, ${pct} more than the period before`,
  fellBy: (pct: string) => `, ${pct} fewer than the period before`,
  fellFrom: (name: string) => `. Most of the drop is ${name}`,
  people: (n: string) => (n === '1' ? '1 person' : `${n} people`),
  visitorsN: (n: number) => (n === 1 ? '1 visitor' : `${n} visitors`),
  topSource: (name: string, pct: string) => `. ${name} sent ${pct} of them`,
  but: (what: string) => `, but ${what}`,
  butAfter: (what: string) => ` But ${what}`,
  oneThenGo: 'most of them leave after one page',
  shorter: 'they stay for a shorter time than before',
  quietNote: (name: string, pct: string) => `Nothing needs you. Your top source, ${name}, sent ${pct} of the visitors.`,
  newNote: 'In about a week trckable knows your normal and starts telling you what changed.',
  // The takeaway and the arrows.
  takeSame: 'About the same as the period before.',
  // The headline already says by how much, so this sentence names the source (or just the direction) and never repeats the percent.
  takeHead: (up: boolean, source?: string, why?: string) => (source ? `Mostly from ${source}${why ?? ''}.` : `${up ? 'Up' : 'Down'} on the period before.`),
  // The one clause that says why, tacked on after the source.
  whyPage: (page: string) => `, most of it on ${page}`,
  whyReferrer: (name: string) => `, most of it from ${name}`,
  whyCampaign: (name: string) => `, most of it from the ${name} campaign`,
  whyCountry: (name: string) => `, most of it from ${name}`,
  takeFollow: (name: string, same: boolean) => {
    const n = name.charAt(0).toUpperCase() + name.slice(1)
    return same ? `${n} followed.` : `${n} did not follow.`
  },
  tenTimes: 'more than 10x',
  tenTimesShort: '10x+',
  whatVisits: 'visits',
  whatRevenue: 'revenue',
  dash: '–',
  /** The chip on an answer: "↑ 12%", "↑ 10x+", or "visits ↑ 12%" where the big number is something else. */
  deltaText: (arrow: string, by: string, what: string) => `${what ? `${what} ` : ''}${arrow} ${by}`,
  deltaWord: { '↑': 'Up', '↓': 'Down', '→': 'Unchanged' },
  deltaLabel: (word: string, by: string, what: string) => `${what ? `${what}: ` : ''}${word} ${by} on the period before`,
  // The tiles.
  visitors: 'Visitors',
  bounce: 'Bounce rate',
  session: 'Session time',
  revenue: 'Revenue',
  tilesLabel: 'Key numbers',
  stripe: 'Stripe',
  notCounted: 'not counted',
  connect: 'Connect Stripe to see it',
  connectChip: 'Connect Stripe',
  noBeforeShort: 'No earlier period yet',
  noBefore: 'No earlier period to compare with yet',
  tooFew: 'Too few visits yet',
  normalTip: 'Normal is the period before this one. It needs a few days of data.',
  farAbove: (before: string) => `Far above your normal (${before} before)`,
  above: (before: string) => `Above your normal (${before} before)`,
  inside: (before: string) => `Inside your normal (${before} before)`,
  below: (before: string) => `Below your normal (${before} before)`,
  farBelow: (before: string) => `Far below your normal (${before} before)`,
  bounceHigh: (n: number) => `High: ${n} in 10 read one page and go`,
  bounceWorse: (before: string) => `Worse than before (${before})`,
  bounceBetter: (before: string) => `Better than before (${before})`,
  bounceSame: (before: string) => `Inside your normal (${before} before)`,
  timeLonger: (before: string) => `Longer than before (${before})`,
  timeShorter: (before: string) => `Shorter than before (${before})`,
  timeSame: (before: string) => `Inside your normal (${before} before)`,
  // The chart and its moments.
  chartTitle: 'What happened, day by day',
  chartHint: (n: number) => `${n} ${n === 1 ? 'moment' : 'moments'} · tap one to open it`,
  chartLabel: 'Visitors over the period, with the moments marked',
  before: 'the period before',
  noMoments: 'Nothing unusual to mark in this period.',
  // The five questions.
  statusBefore: 'vs before',
  statusSoFar: 'so far',
  statusPage: 'of visits',
  statusBounce: 'bounce rate',
  statusRevenue: 'of revenue',
  statusGoal: 'times',
  none: 'None yet',
  noIssues: '0 issues',
  questionsTitle: 'Your five questions, answered',
  q: bar.q,
  didYes: (a: string, b: string) => `Yes. Visitors went from ${a} to ${b}.`,
  didNo: (a: string, b: string) => `Not yet. Visitors went from ${a} to ${b}.`,
  didSame: (a: string, b: string) => `About the same as before: ${b} visitors, ${a} then.`,
  didEarly: (who: string) => `Too early to say. ${who} so far and no earlier period to compare with.`,
  didSub: (n: string, pct: string, name: string) => `${n} people (${pct}) came from ${name}, your biggest source.`,
  didAct: (name: string) => `See ${name}'s numbers`,
  pageTitle: (page: string, pct: string) => `${page} is where ${pct} of visits start.`,
  pageSub: (n: string) => `${n} people landed there first. Link your other pages from it so they keep reading.`,
  pageNone: 'No page stands out yet.',
  pageNoneSub: 'Once there are more visits, the page most people land on shows up here.',
  pageAct: "Open the page's numbers",
  fixTitle: (name: string, pct: string) => `${name} visitors leave fastest: ${pct} read one page and go.`,
  fixSub: (n: string, best: string, bestPct: string) => `That is ${n} people. ${best} visitors do better: ${bestPct}.`,
  fixSubAlone: (n: string) => `That is ${n} people.`,
  fixFew: 'Not enough visits yet.',
  fixFewSub: 'Once more people have visited, this shows which source loses them fastest.',
  fixNone: 'Nothing stands out to fix.',
  fixNoneSub: 'No source loses its visitors much faster than the others.',
  fixAct: 'Show where they land',
  paysTitle: (name: string, pct: string) => `${name} brings ${pct} of your money.`,
  paysSub: (part: string, whole: string) => `${part} of ${whole}.`,
  paysGoal: (name: string, n: string) => `${name} is your top goal: ${n} times.`,
  paysGoalSub: 'Sales are not counted yet. Connect a payment provider and this line says which source pays.',
  paysNone: 'Not known yet: no sales or sign-ups are counted.',
  paysNoneSub: 'Once they are, this line says which source brings the money.',
  paysAct: (name: string) => `See what ${name} sold`,
  paysGoalAct: 'See the goal',
  paysCount: 'Count a sign-up',
  fineEarly: 'Too early to judge.',
  fineEarlySub: 'There is no earlier period to measure against yet.',
  fineGood: 'A good period. Nothing is worse than before.',
  fineMixed: (worse: string) => `Mostly good. Only ${worse} is worse than before.`,
  fineBad: (worse: string) => `Not a good period. ${worse} are worse than before.`,
  fineSame: 'A steady period. Everything is about where it was.',
  fineSub: 'Measured against your own period before, never against made-up averages.',
  fineAct: 'Compare with before',
  wordEarly: 'Too early',
  wordSame: 'Steady',
  wordGood: 'Good',
  wordMixed: 'Mostly good',
  wordBad: 'Not good',
  // Asking, and the verdict.
  useful: 'Was this useful?',
  yes: 'Yes',
  no: 'Not really',
  yesLabel: 'Yes, useful',
  noLabel: 'No, not useful',
  tellUs: 'Tell us what you came for',
  askLabel: 'What did you open trckable to find out today?',
  askPlaceholder: 'e.g. did my newsletter work?',
  askSend: 'Send',
  askClose: 'Close',
  thanks: 'Thanks.',
  exploreAll: 'Explore all the numbers: Sources, Pages, Locations, Devices, Calendar',
  loading: 'Reading your numbers',
})
