// The words of milestones: the moment, the timeline and the share sheet.
// The dashboard's text moves to message files when translations come, and
// this is what moves.
import { defineCopy } from '../../i18n'

export const copy = defineCopy('milestones', {
  // What each family's number is.
  label: {
    visitors: 'visitors',
    pageviews: 'pageviews',
    firstPageview: 'First pageview',
    record_day: 'visitors · record day',
    countries: 'countries',
    first_goal: 'First goal',
    first_sale: 'First sale',
    revenue: 'revenue',
  },
  first: '1st',
  title: 'Milestones',
  menu: 'Milestones',
  share: 'Share',
  replay: 'Replay',
  close: 'Close',
  dismiss: 'Dismiss',
  // The window.
  newMilestone: 'New milestone',
  today: 'today',
  almostThere: 'Almost there',
  shareCard: 'Share the card',
  replayWay: 'Replay the way there',
  nextUp: 'Next up',
  reachedIn: (year: string) => `Reached in ${year}`,
  toGo: (n: string) => `${n} to go`,
  revenueQuiet: 'Revenue milestone',
  noSaleYet: 'no sale yet',
  replayOf: (label: string) => `Replay ${label}`,
  shareOf: (label: string) => `Share ${label}`,
  // One sentence per family, under the big number.
  line: {
    visitors: (n: string) => `${n} people have visited your site.`,
    pageviews: (n: string) => `Your pages have been viewed ${n} times.`,
    firstPageview: 'Your site counted its first pageview.',
    record_day: (n: string) => `${n} visitors in one day: your busiest yet.`,
    countries: (n: string) => `People from ${n} countries have visited your site.`,
    first_goal: 'A visitor reached one of your goals for the first time.',
    first_sale: 'Your first sale came in.',
    revenue: (n: string) => `Your site has earned ${n}.`,
    revenueQuiet: 'Your revenue reached a new step.',
  },
  progress: (now: string, step: string, label: string) => `${now} of ${step} ${label}`,
  progressDays: (now: string, step: string, label: string, days: number) => `${now} of ${step} ${label} · ~${days} ${days === 1 ? 'day' : 'days'} at this pace`,
  quietStep: 'Reached',
  next: (step: string, label: string, now: string) => `next ${step} ${label} · ${now} now`,
  none: 'Nothing yet. The first one is 100 visitors.',
  off: 'Milestones are off for this site.',
  // The share sheet.
  sheet: 'Share milestone',
  copyLink: 'Copy link',
  copied: 'Link copied',
  linkOnce: 'The link is shown once. Revoke it to make a new one.',
  shared: 'Link active',
  revoke: 'Revoke link',
  revoked: 'Link revoked',
  download: 'Download PNG',
  copyImage: 'Copy image',
  imageCopied: 'Image copied',
  email: 'Email to…',
  showAmount: 'Show amount',
  light: 'Light card',
  dark: 'Dark card',
  card: 'Card preview',
  mailSubject: (line: string) => line,
  // Settings.
  setting: 'Milestones',
  settingHint: 'A quiet note when the site reaches a round number',
})
