// The Share dialog's words (features/share): what moves to the message files
// when translations come.
export const copy = {
  title: 'Share your numbers',
  subtitle: 'A card for a post, drawn from this site.',
  close: 'Close',
  period: 'Period',
  templates: 'Card',
  periods: { '24h': '24 hours', '7d': '7 days', '30d': '30 days' },
  template: {
    spotlight: { name: 'Spotlight', hint: 'One big number' },
    leaderboard: { name: 'Leaderboard', hint: 'Top pages' },
    dashboard: { name: 'Dashboard', hint: 'The chart' },
    post: { name: 'Social post', hint: 'A quick text' },
  },
  site: 'Site',
  light: 'Light card',
  dark: 'Dark card',
  accent: 'Accent',
  metric: 'Number',
  metrics: { visitors: 'Visitors', pageviews: 'Pageviews', revenue: 'Revenue' },
  download: 'PNG',
  downloadTitle: 'Download PNG',
  copyText: 'Copy',
  copied: 'Copied',
  saved: 'Saved',
  previewAlt: (name: string) => `${name} card`,
  failed: "The card couldn't be drawn",
  link: 'Link',
  linkTitle: 'A read-only link to this site',
  password: 'Password',
  passwordHint: 'Optional',
  revenue: 'Revenue',
  create: 'Create link',
  copyLink: 'Copy link',
  linkCopied: 'Link copied',
  back: 'Back',
  manage: 'All links are in Settings → Sharing',
  // The look of this site's links: the owner's own logo, colour and domain.
  preview: 'Preview of the shared page',
  previewSample: 'Shared with you',
  previewPath: '/s/…',
  tiles: ['Visitors', 'Pageviews', 'Bounce rate', 'Session time'],
  look: 'Look of the links',
  lookInfo: 'What people see when they open a link: your logo and colour instead of trckable’s, and optionally your own domain.',
  logo: 'Logo',
  logoHint: 'PNG, JPEG, GIF or SVG, up to 128 KB',
  logoRefused: 'That logo can’t be used. Use a PNG, JPEG, GIF or an SVG without scripts or links.',
  logoBig: 'A logo can be up to 128 KB',
  upload: 'Upload',
  remove: 'Remove',
  colour: 'Colour',
  resetColour: 'Reset',
  hideBrand: 'Hide trckable branding',
  domain: 'Domain',
  domainHint: 'reports.example.com',
  domainRefused: 'That domain can’t be used. Write the host only, like reports.example.com; it may belong to another site.',
  cname: (domain: string, target: string) => `${domain} CNAME ${target}`,
  cnameInfo: 'First show the domain is yours with a TXT record, then point it at your server with a CNAME record. Your proxy provides the https.',
  txt: (name: string, value: string) => `${name} TXT ${value}`,
  check: 'Check',
  verified: 'Verified',
  notYet: 'The record was not found yet. DNS can take a while.',
}
