// The two cards under the chart: their tabs, and the small words on their lists.
import { defineCopy } from '../../i18n'
import { fmtInt } from '../../lib/format'

export const cardCopy = defineCopy('cards', {
  who: 'Who came',
  what: 'What they did',
  sources: 'Sources',
  pages: 'Pages',
  locations: 'Locations',
  devices: 'Devices',
  channels: 'Channels',
  referrers: 'Referrers',
  campaigns: 'UTM',
  entry: 'Landing pages',
  top: 'Most viewed',
  exit: 'Exit',
  sections: 'Sections',
  scroll: 'Scroll',
  goals: 'Goals',
  earners: 'Sources that pay',
  trackGoal: '+ Track a goal',
  goal: 'Goal',
  conv: 'Conv.',
  goalOutbound: 'Outbound click',
  goalDownload: 'File download',
  goalForm: 'Form submit',
  goalVisitors: (n: number) => (n === 1 ? '1 visitor' : `${fmtInt(n)} visitors`),
  ofVisitors: 'of visitors',
  funnelTitle: 'From visit to goal',
  funnelVisitors: 'Visitors',
  funnelEngaged: 'Read past the first page',
  donutLabel: 'visitors',
  sharesFoot: 'Shares are of all visitors; someone can appear in more than one row.',
  noGoals: 'Goals appear here after the first visit, click or event.',
  perDayChannels: 'Per-day data covers channels only',
  perDayEntry: 'Per-day data covers entry pages only',
  loading: 'Loading',
  heatmap: (page: string) => `Heatmap of ${page}`,
})
