// The two cards under the chart: their tabs, and the small words on their lists.
export const cardCopy = {
  who: 'Who came',
  what: 'What they did',
  sources: 'Sources',
  pages: 'Pages',
  locations: 'Locations',
  devices: 'Devices',
  channels: 'Channels',
  referrers: 'Referrers',
  campaigns: 'UTM',
  search: 'Search',
  entry: 'Entry',
  top: 'Top',
  exit: 'Exit',
  sections: 'Sections',
  scroll: 'Scroll',
  countries: 'Countries',
  regions: 'Regions',
  cities: 'Cities',
  map: 'Map',
  device: 'Devices',
  browser: 'Browsers',
  os: 'OS',
  goals: 'Goals',
  earners: 'Sources that pay',
  ai: 'AI',
  trackGoal: '+ Track a goal',
  goal: 'Goal',
  conv: 'Conv.',
  noGoals: 'No goals yet.',
  credit: 'Which visit gets the credit',
  closedIt: 'Closed it',
  foundThem: 'Found them',
  page: 'Page',
  customers: 'Customers',
  perVisitor: 'Per visitor',
  wholePeriod: 'Whole-period view only',
  noRevenue: 'No attributed revenue yet. Pass trckable_vid to your checkout (Settings → Payments).',
  perDayChannels: 'Per-day data covers channels only',
  perDayEntry: 'Per-day data covers entry pages only',
  perDayDevice: 'Per-day data covers device type only',
  loading: 'Loading',
}
