// The words of Settings → Alerts → Client reports.
export const copy = {
  title: 'Client reports',
  subtitle: 'The numbers, by email, on a schedule',
  needsMail: 'Needs email (TRCKABLE_SMTP_URL) and TRCKABLE_BASE_URL on this server',
  none: 'No reports yet',
  add: 'Add a report',
  untitled: 'Report',
  weekly: 'Weekly',
  monthly: 'Monthly',
  pdf: 'PDF',
  to: (n: number) => (n === 1 ? '1 address' : `${n} addresses`),
  nobody: 'No addresses',
  off: 'Off',
  lastSent: (when: string) => `Last sent ${when}`,
  never: 'Not sent yet',
  on: (name: string) => `${name}: on`,
  turnedOff: (name: string) => `${name}: off`,
  edit: 'Edit',
  remove: 'Delete',
  test: 'Send me a test',
  testSent: (to: string) => `Sent to ${to}`,
  name: 'For',
  namePlaceholder: 'Client or team',
  cadence: 'How often',
  language: 'Language',
  attachPdf: 'Attach a PDF',
  recipients: 'Addresses',
  recipientsHint: (max: number) => `One per line, up to ${max}`,
  save: 'Save',
  cancel: 'Cancel',
  saved: 'Saved',
  removed: 'Report deleted',
  removeTitle: (name: string) => `Delete “${name}”?`,
  removeBody: 'It stops being sent. Nothing else changes.',
  langNames: { en: 'English', de: 'Deutsch', fr: 'Français', es: 'Español', it: 'Italiano', nl: 'Nederlands' } as Record<string, string>,
}
