// The words of Settings → Alerts → Client reports.
import { defineCopy } from '../../i18n'

const langNames: Record<string, string> = { en: 'English', de: 'Deutsch', fr: 'Français', es: 'Español', it: 'Italiano', nl: 'Nederlands' }

export const copy = defineCopy('reports', {
  title: 'Client reports',
  subtitle: 'The numbers, by email, on a schedule',
  needsMail: 'Reports need email on this server',
  setup: 'How to set it up',
  setupUrl: 'https://trckable.com/docs/self-host/configuration/',
  none: 'No reports yet',
  add: 'Add a report',
  untitled: 'Report',
  weekly: 'Weekly',
  monthly: 'Monthly',
  pdf: 'PDF',
  to: (n: number) => (n === 1 ? '1 address' : `${n} addresses`),
  nobody: 'No addresses',
  off: 'Off',
  lastSent: (when: string) => `Last sent ${when}`,
  never: 'Not sent yet',
  on: (name: string) => `${name}: on`,
  turnedOff: (name: string) => `${name}: off`,
  edit: 'Edit',
  remove: 'Delete',
  test: 'Send now',
  testSent: (to: string) => `Sent to ${to}`,
  name: 'For',
  namePlaceholder: 'Client or team',
  cadence: 'How often',
  language: 'Language',
  attachPdf: 'Attach a PDF',
  recipients: 'Addresses',
  recipientsHint: (max: number) => `One per line, up to ${max}`,
  save: 'Save',
  cancel: 'Cancel',
  newTitle: 'New report',
  editTitle: 'Edit report',
  who: 'Who it is for',
  how: 'What they get',
  summary: 'Summary',
  pause: 'Pause',
  resume: 'Resume',
  paused: 'Paused',
  saved: 'Saved',
  removed: 'Report deleted',
  removeTitle: (name: string) => `Delete “${name}”?`,
  removeBody: 'It stops being sent. Nothing else changes.',
  langNames,
})
