// Every word of Settings → Sharing: loaded with it, never with the first screen.
import type { Share } from '../../lib/api'
import { defineCopy } from '../../i18n'

export const copy = defineCopy('links', {
  title: 'Share these numbers',
  tip: 'A read-only link to this one site: no account, nothing to change. With revenue off, the server never sends the figure.',
  empty: 'No links yet',
  newLink: 'New link',
  name: 'Name',
  namePlaceholder: 'For the investors',
  public: 'Public',
  password: 'Password',
  passwordOnly: 'Anyone with the link, and the password',
  publicOnly: 'Anyone with the link',
  mode: 'Who can open it',
  revenue: 'Revenue',
  notes: 'Notes',
  expires: 'Expires',
  never: 'Never',
  d7: '7d',
  d30: '30d',
  pickDate: 'Pick a date',
  date: 'End date',
  dateBad: 'Pick a day up to ten years ahead',
  embed: 'Embed on sites',
  embedField: 'Site addresses',
  embedPlaceholder: 'https://example.com',
  embedBad: (s: string) => `${s} is not a site address`,
  embedNeed: 'Add a site address',
  embedMany: (n: number) => `${n} sites at most`,
  cancel: 'Cancel',
  create: 'Create link',
  creating: 'Creating…',
  needPassword: 'Set a password',
  copy: 'Copy',
  copied: 'Copied',
  copiedToast: 'Link copied',
  copyFailed: 'Could not copy',
  copyRow: (name: string) => `Copy link: ${name}`,
  open: 'Open',
  openRow: (name: string) => `Open link: ${name}`,
  newAddress: 'New address',
  newAddressTip: "This address can't be shown. Make a new one to copy.",
  newAddressRotate: 'Make a new address',
  newAddressAsk: 'The old address stops working.',
  newAddressing: 'Making…',
  qr: 'QR code',
  qrLabel: 'QR code of the link',
  embedCode: 'Embed code',
  embedCopied: 'Embed code copied',
  done: 'Done',
  preview: 'Preview',
  lockScreen: 'Show the password screen',
  pageScreen: 'Show the page',
  lockedTitle: 'Password',
  lockedField: '••••••••',
  ends: (d: string) => `Ends ${d}`,
  rangeLabel: 'Last 30 days',
  visitors: 'Visitors',
  views: 'Views',
  bounce: 'Bounce',
  sources: 'Sources',
  revenueByPage: 'Revenue by page',
  fixed: 'Fixed once the link is made',
  revenueOn: 'Revenue shown',
  revenueOff: 'Revenue hidden',
  embedOn: (origins: string[]) => `Embeddable on ${origins.join(', ')}`,
  embedOff: 'Not embeddable',
  notesOn: (name: string) => `Notes shown: ${name}`,
  notesOff: (name: string) => `Notes hidden: ${name}`,
  notesTip: (on: boolean) => (on ? 'Notes shown. Click to hide' : 'Notes hidden. Click to show'),
  notesShown: 'This link shows the notes now',
  notesHidden: 'This link hides the notes now',
  rowPassword: 'Password link',
  rowPublic: 'Public link',
  noEnd: 'No end date',
  ended: (d: string) => `Ended ${d}`,
  neverOpened: 'Never opened',
  lastOpened: (d: string) => `Last opened ${d}`,
  viewsLabel: (n: number) => `${n} ${n === 1 ? 'view' : 'views'}`,
  revoke: (name: string) => `Revoke ${name}`,
  revokeAsk: 'Revoke it?',
  revokeYes: 'Revoke',
  revoking: 'Revoking…',
  revoked: 'Link revoked',
  keep: 'Keep',
  fallbackName: 'Shared link',
  changeFailed: 'Could not change the link',
})

/** What a link is called when its name is empty. */
export const nameOf = (s: Pick<Share, 'name'>) => s.name || copy.fallbackName
