// Turns the 110m world atlas into a tiny file of SVG paths, once, at build
// time. The dashboard then draws the map with no map library, no projection
// code and no network request: just <path d="…"> per country.
//
// Run with `npm run build:map` after changing anything here.
import { writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const topo = require('world-atlas/countries-110m.json')
const { feature } = require('topojson-client')
const iso = require('iso-3166-1')

const W = 1000 // the SVG's own coordinate box
const H = 500

// Equirectangular: the honest, boring choice. Areas near the poles stretch,
// but every country keeps its place and the maths is two multiplications.
const px = (lon) => ((lon + 180) / 360) * W
const py = (lat) => ((90 - lat) / 180) * H

// The map is read at a glance, not zoomed: dropping points that move the
// outline less than a pixel (and specks smaller than a few pixels) halves the
// file without changing what anyone sees.
const EPS = 1.2
const MIN_AREA = 6

function simplify(ring) {
  const out = [ring[0]]
  for (let i = 1; i < ring.length - 1; i++) {
    const [x, y] = ring[i]
    const [lx, ly] = out[out.length - 1]
    if (Math.abs(x - lx) + Math.abs(y - ly) >= EPS) out.push(ring[i])
  }
  out.push(ring[ring.length - 1])
  return out
}

/** Shoelace area, to skip islands too small to see. */
function area(pts) {
  let a = 0
  for (let i = 0, j = pts.length - 1; i < pts.length; j = i++) a += pts[j][0] * pts[i][1] - pts[i][0] * pts[j][1]
  return Math.abs(a / 2)
}

function pathOf(geometry) {
  const polys = geometry.type === 'Polygon' ? [geometry.coordinates] : geometry.coordinates
  let d = ''
  for (const poly of polys) {
    for (const ring of poly) {
      const pts = simplify(ring.map(([lon, lat]) => [px(lon), py(lat)]))
      if (pts.length < 4 || area(pts) < MIN_AREA) continue // a speck: not worth the bytes
      d += 'M' + pts.map(([x, y]) => `${Math.round(x)},${Math.round(y)}`).join('L') + 'Z'
    }
  }
  return d
}

const countries = feature(topo, topo.objects.countries).features
const out = []
for (const f of countries) {
  const rec = iso.whereNumeric(String(f.id).padStart(3, '0'))
  const d = pathOf(f.geometry)
  if (!d) continue
  // Kosovo has no ISO code; keep it under the code MaxMind and DB-IP use.
  const code = rec?.alpha2 ?? (f.properties.name === 'Kosovo' ? 'XK' : null)
  if (!code) continue
  out.push([code, d])
}
out.sort((a, b) => (a[0] < b[0] ? -1 : 1))

const body = `// Generated by scripts/build-map.mjs from world-atlas 110m. Do not edit.
// ${out.length} countries, equirectangular, in a ${W}×${H} box.
export const MAP_W = ${W}
export const MAP_H = ${H}
export const COUNTRIES: [string, string][] = ${JSON.stringify(out)}
`
writeFileSync(new URL('../src/lib/worldmap.ts', import.meta.url), body)
console.log(`${out.length} countries, ${(body.length / 1024).toFixed(1)} KB raw`)
