// The words of the All sites chart (AllSitesChart.tsx).
import { defineCopy } from '../i18n'

export const copy = defineCopy('allsites', {
  empty: 'No visits in this period yet.',
  label: 'Visitors per day, every site stacked',
  other: 'Other sites',
  all: 'All sites',
  site: 'Site',
  online: 'Online now',
  onlineSub: 'in the last 5 minutes',
  visitors: 'Visitors',
  vsBefore: (change: string, days: number) => `${change} vs the ${days} days before`,
  pageviews: 'Pageviews',
  perVisitor: (n: string) => `${n} per visitor`,
  bounce: 'Bounce rate',
  acrossSites: 'across these sites',
  revenue: 'Revenue',
  fromSites: (n: number) => (n === 1 ? 'from 1 site' : `from ${n} sites`),
  currencies: (n: number) => `${n} currencies`,
  onlineNow: (n: string) => `${n} online now`,
  noOne: 'No one online',
  bounceShort: (p: string) => `bounce ${p}`,
  bounceHigh: (p: string, words: string) => `Bounce rate ${p}, ${words}`,
  highBounce: (tenths: number) => `high: ${tenths} in 10 leave after one page`,
  unread: 'could not be read',
  waiting: 'Waiting for the first visit',
  install: 'Install the script →',
  notConnected: 'Not connected',
  connect: 'Connect payments →',
  sort: (by: string) => `Sort: ${by}`,
  sortLabel: 'Sort sites by',
  viewLabel: 'View',
  viewCards: 'Cards',
  viewList: 'List',
  byVisitors: 'Visitors',
  byName: 'Name',
  share: (p: number) => `${p}% of all visitors`,
  since: (day: string) => `Tracking since ${day}`,
})
