// Every word of Settings → Widgets that is not a design's own name: in one
// place, so the message files can translate it.
import { defineCopy } from '../i18n'

export const copy = defineCopy('widgets', {
  stage: { title: 'Widget preview', tone: 'Page tone', view: 'View', light: 'Light', dark: 'Dark', alone: 'Alone', page: 'On a page' },
  section: { look: 'Look', placement: 'Placement', language: 'Language & texts', brand: 'Brand', show: 'Show' },
  text: {
    pageTitle: 'Widgets',
    pageHint: 'A small card with live numbers, for your own pages. It runs no script and sets no cookie, and only the numbers it shows are public.',
    newWidget: 'New widget',
    ready: 'Widget ready: copy it onto your page',
    done: 'Done',
    none: 'No widgets yet',
    mode: 'Mode',
    show: 'Show',
    theme: 'Theme',
    colour: 'Colour',
    corners: 'Corners',
    placement: 'Placement',
    nameLabel: 'Name',
    only: ' · only in trckable',
    edit: 'Edit',
    rename: 'Rename',
    delete: 'Delete',
    menu: 'Widget menu',
    name: 'Widget name',
    editTitle: 'Edit widget',
    editHint: 'The code on your pages stays the same',
    make: ['Make this widget', 'Making it…'],
    save: 'Save changes',
    saving: 'Saving…',
    cancel: 'Cancel',
    saved: 'Widget saved. Pages that show it follow within a minute',
    language: 'Language',
    texts: 'Texts',
    credit: 'Show "Counted by trckable"',
    textsHint: 'Leave empty for the translated default',
    frame: 'Paste this where the card should appear',
    corner: 'Or paste this once, to float it in a corner of every page. Visitors can close it',
    copyFrame: 'Copy embed code',
    copyCorner: 'Copy the corner script',
    snippet: 'Snippet copied',
    newCode: 'Copy the new code to get auto height',
    script: 'Script copied',
  },
})
