// The Data view's overview words: its tiles and the main chart's head. What
// moves to the message files when translations come.
export const copy = {
  replay: 'Replay this period day by day',
  replayByHour: 'Replay this period hour by hour',
  replayByDay: 'Replay this period day by day (switches the chart to days)',
  pause: 'Pause replay',
  scrub: 'Scrub through the period',
  speed: 'Replay speed',
  speedNow: (name: string) => `Replay speed: ${name}`,
  playsIn: (time: string) => `plays in ${time}`,
  speedKeys: 'Slower [  Faster ]',
  wholePeriod: 'the whole period',
  backToPeriod: (day: string) => `Viewing ${day}: back to the whole period`,
  chartTile: (label: string) => `Chart ${label.toLowerCase()}`,
  change: (label: string, vs: string) => `${label} ${vs}`,
  keyNumbers: 'Key numbers',
  revenue: 'Revenue',
  visitors: 'Visitors',
  pageviews: 'Pageviews',
  bounce: 'Bounce rate',
  session: 'Session time',
  perVisitorTile: 'Per visitor',
  perVisitor: 'Revenue / visitor',
  perVisitorShort: '$/visit',
  conversion: 'Conversion',
  conversionShort: 'conv.',
  sales: (n: number) => (n === 1 ? '1 sale' : `${n} sales`),
  newAmount: (amount: string) => `${amount} new`,
  renewalAmount: (amount: string) => `${amount} renewal`,
}
