// Every word on the API keys tab.
export const keys = {
  title: 'API keys',
  max: 20,
  count: (used: number, max: number) => `${used} / ${max}`,
  create: 'Create key',
  creating: 'Creating…',
  cancel: 'Cancel',
  nameLabel: 'Key name',
  namePlaceholder: 'Claude on my laptop',
  defaultName: 'API key',
  tiles: {
    ai: 'Your AI (MCP)',
    api: 'API',
    scripts: 'Scripts',
  },
  docs: 'https://trckable.com/docs/api/mcp/',
  apiDocs: 'https://trckable.com/docs/api/',
  never: 'never',
  lastUsed: (when: string) => `last used ${when}`,
  secretLabel: 'Your new key',
  copy: 'Copy',
  copied: 'Copied',
  copiedToast: 'Key copied',
  close: 'Close',
  revokeLabel: (name: string) => `Revoke ${name}`,
  revoke: 'Revoke',
  revokeTitle: (name: string) => `Revoke "${name}"?`,
  revokeUsed: 'Anything using this key stops working immediately, and this cannot be undone.',
  revokeUnused: 'This key has never been used. Revoking it cannot be undone.',
  revoking: 'Revoking…',
  revoked: 'Key revoked',
  ago: {
    now: 'just now',
    minutes: (n: number) => `${n} min ago`,
    hours: (n: number) => `${n} h ago`,
    yesterday: 'yesterday',
    days: (n: number) => `${n} days ago`,
  },
}
