// Every word on the People tab, outside the sentences a dialog asks.
export const people = {
  title: 'People',
  add: 'Add someone',
  adding: 'Adding…',
  addGo: 'Add',
  cancel: 'Cancel',
  emailLabel: 'Email',
  emailPlaceholder: 'them@company.com',
  owner: 'Owner',
  viewer: 'Viewer',
  you: 'You',
  roleLabel: 'Role',
  roleTip: 'Owners change everything; viewers only look',
  roleOf: (email: string) => `Role of ${email}`,
  lockSelf: 'Your own role is changed by another owner',
  lockLast: 'The only owner: make someone else an owner first',
  lockHolder: 'The first owner keeps this role',
  waiting: 'Waiting to sign in',
  sitesLabel: 'Sites',
  sites: {
    all: 'All sites',
    none: 'No sites',
    some: (n: number, of: number) => `${n} of ${of} sites`,
    of: (n: number, of: number) => `${n} of ${of}`,
    find: 'Find a site',
    empty: 'No site found',
    done: 'Done',
    failed: 'The sites were not saved',
    allWhy: 'Including sites added later',
  },
  /** The pill and its popover: what each role may do, in one line. */
  roles: {
    owner: { name: 'Owner', what: 'Runs everything: sites, payments, people, keys.' },
    viewer: { name: 'Viewer', what: 'Reads the sites you allow. Changes nothing.' },
  },
  rolePill: (email: string, role: string) => `Role of ${email}: ${role}`,
  /** The confirmation before a role changes. */
  change: {
    ownerTitle: (name: string) => `Make ${name} an owner?`,
    viewerTitle: (name: string) => `Make ${name} a viewer?`,
    ownerLines: ['Sees and changes every site', 'Adds and removes people, you too', 'Connects payments, creates keys'],
    viewerLines: ['Can no longer change anything', 'Still sees every site until you pick fewer.'],
    trust: 'I trust them with all of this',
    cancel: 'Cancel',
    ownerGo: 'Make owner',
    viewerGo: 'Make viewer',
    busy: 'Saving…',
    failed: 'The role was not changed',
    nowOwner: (name: string) => `${name} is now an owner`,
    nowViewer: (name: string) => `${name} is now a viewer`,
  },
  status: {
    active: 'Active',
    waiting: 'Not signed in yet',
    twoStep: 'Two-step is on',
  },
  menu: {
    options: (email: string) => `${email} options`,
    profile: 'Your account settings',
    sites: 'Allowed sites',
    reset: 'New sign-in details',
    twoStepOff: 'Turn off two-step',
    remove: 'Remove',
  },
  reset: {
    title: (email: string) => `New sign-in details for ${email}?`,
    body: 'They are signed out everywhere, get a new one-time password from you, and choose their own at the next sign-in. Type your own password to confirm.',
    confirm: 'Make new details',
    busy: 'Resetting…',
  },
  twoStepOff: {
    title: (email: string) => `Turn off two-step for ${email}?`,
    body: 'For a lost phone with no recovery codes left: they sign in with their password alone, then set two-step up again. Type your own password to confirm.',
    confirm: 'Turn off two-step',
    busy: 'Turning off…',
    done: (email: string) => `Two-step is off for ${email}`,
  },
  remove: {
    title: (email: string) => `Remove ${email}?`,
    body: 'They are signed out everywhere straight away. Nothing they looked at is deleted.',
    confirm: 'Remove',
    busy: 'Removing…',
    done: (email: string) => `${email} removed`,
  },
  own: {
    password: 'Your password',
    next: 'Next',
    codeTitle: 'A code from your app',
    codeBody: 'Your own two-step is on: the six digits your authenticator shows now, or one of your recovery codes.',
    code: 'Code',
  },
  otp: {
    label: 'Their one-time password',
    titleNew: 'Send them this password',
    titleReset: 'Their new one-time password',
    body: (email: string) => `Shown once. ${email} signs in with it and chooses their own right away. trckable sends no email: pass it on however you like.`,
    copy: 'Copy',
    copied: 'Copied',
    copyAll: 'Copy with sign-in details',
    done: 'Done',
    message: (origin: string, email: string, password: string) =>
      `Sign in to trckable at ${origin} as ${email} with this one-time password: ${password}\nYou will choose your own right after.`,
  },
}
