// Glance's words (English only: a prototype).
import { defineCopy } from '../../i18n'

export const copy = defineCopy('glance', {
  formatLabel: 'Data format',
  charts: 'Charts',
  glance: 'Glance',
  chartsTip: 'Charts: every number, as today',
  glanceTip: 'Glance: the short version',
  section: 'At a glance',
  people: 'people',
  stripLabel: (period: string) => `People per day, ${period}`,
  barTitle: (day: string, n: string) => `${day}: ${n} people`,
  best: 'best day',
  today: 'Today',
  openPeriod: 'Change period',
  // Verdict
  growing: 'Growing',
  slowing: 'Slowing down',
  steady: 'Steady',
  starting: 'Getting started',
  firstMonth: 'your first month',
  level: (n: string) => `steady at ~${n} a day`,
  levelFirst: (n: string) => `about ${n} a day`,
  bestDay: (day: string) => `best day ${day}`,
  comparisonsStart: (date: string) => `Comparisons start on ${date}`,
  // Alerts
  seeWhy: 'See why →',
  alertBounce: (n: number) => `${n} in 10 people leave after one page.`,
  alertBounceSub: ' Make your first page lead somewhere.',
  alertDown: (period: string) => `Fewer people than last ${period}.`,
  alertDownSub: ' Check where they come from.',
  alertSource: (name: string) => `${name} sent far fewer people.`,
  alertSourceSub: ' See what changed there.',
  alertQuiet: (when: string) => `We haven't received data since ${when}.`,
  alertQuietSub: ' Check that the script is still on your pages.',
  periodWord: 'period',
  // Tiles
  tilesLabel: 'Details',
  hint: 'Tap any tile for the full picture: chart, every row, compare and export.',
  tSource: 'Where they come from',
  tCarrying: 'Carrying you',
  tStaying: 'Staying',
  tReading: 'Reading time',
  tDevice: 'Reading on',
  tCountry: 'Where they are',
  tGoals: 'Goals',
  tRevenue: 'Revenue',
  none: '–',
  noData: 'No data for this yet.',
  notSet: 'Not set',
  notCounted: 'Not counted',
  onePage: '1 article',
  leave: (pct: string) => `${pct} leave`,
  mSource: (p1: string, top: string, second?: string, p2?: string) => `${p1} found you on ${top}.${second ? ` ${second} brings ${p2}.` : ''}`,
  mCarrying: (p: string) => `One page starts ${p} of all visits.`,
  mStaying: (n: number) => `${n} in 10 read one page and go.`,
  mReading: (long: boolean) => (long ? 'People who stay really read.' : 'Most people look and move on.'),
  mDevice: (p: string, phone: boolean) => (phone ? `${p} on a phone. Check pages on mobile first.` : `${p} of visits.`),
  mCountry: (p: string, c2?: string, c3?: string) => `${p} of readers.${c2 ? ` ${c2}${c3 ? ` and ${c3}` : ''} follow.` : ''}`,
  mGoalsSetup: 'Count what matters: a sign-up, a click, a visit to a page.',
  mGoals: (n: string, name: string) => `${name} happened ${n} times.`,
  mRevenueSetup: 'See which source pays. Connect Stripe to count sales.',
  mRevenue: (pay: string, name: string) => `${name} brings the most money: ${pay}.`,
  // Panel
  panelTitle: (label: string, period: string) => `${label} · ${period}`,
  compare: 'Compare',
  export: 'Export',
  close: 'Close',
  panel: (label: string) => `${label}: details`,
  closePanel: 'Close panel',
  addFilter: '+ Filter',
  removeFilter: (name: string) => `Remove ${name}`,
  filterHint: 'Pick a row to filter the whole page by it.',
  dimName: { channel: 'Source', entry_page: 'Page', device: 'Device', country: 'Country', goal: 'Goal' },
  colVisitors: 'Visitors',
  colLeave: 'Leave',
  sortBy: (col: string) => `Sort by ${col}`,
  chartLabel: (what: string) => `${what} per day`,
  chartVisitors: 'People',
  chartLeave: 'Leave rate',
  chartTime: 'Time per visit',
  chartRevenue: 'Revenue',
  sSource: (top: string, p: string) => `${top} sends most of your people (${p}). Look at what the others could do.`,
  sCarrying: (page: string) => `${page} starts most visits. Link your other pages from it so people keep reading.`,
  sStaying: 'Most people read one page and go. Add a clear next step to your busiest page.',
  sReading: 'The longer people stay, the more they read. Compare it between sources below.',
  sDevice: 'Open your busiest page on the device most people use.',
  sCountry: 'These are the countries your readers are in. Write for them first.',
  sGoals: (name: string) => `${name} is your top goal. See which source brings it.`,
  sRevenue: 'Sources ordered by the people they bring. Money attribution is in the charts format.',
  setupGoalTitle: 'You are not counting any goal yet.',
  setupGoalBody: 'A goal is one thing you want visitors to do: sign up, buy, or reach a page. It takes two minutes.',
  setupGoalCta: 'Set a goal · 2 min',
  setupRevenueTitle: 'Revenue is not counted yet.',
  setupRevenueBody: 'Connect Stripe and every sale is tied to the visit that brought it, so you see which source pays.',
  setupRevenueCta: 'Connect Stripe',
  helpTitle: 'No data is coming in.',
  helpBody: 'Check that the script is still on your pages, and that no blocker removes it.',
  // States
  couldNot: "Couldn't load",
  retry: 'Retry',
  loading: 'Loading',
  // Search
  find: 'Find anything',
  findLabel: 'Search pages, sources, countries',
  findPlaceholder: 'Search pages, sources, countries, devices, goals',
  findEmpty: 'Nothing matches that.',
  findResults: (n: number) => `${n} results`,
  kinds: { page: 'Page', source: 'Source', country: 'Country', device: 'Device', goal: 'Goal' },
  paletteLabel: 'Search',
  visitorsN: (n: string) => `${n} visitors`,
})
