// The picture of each feature, kept out of the registry so the avatar menu
// (which only needs the ids) does not carry them.
import { Activity, Ban, Banknote, Bot, ClipboardList, Clock, Code, Coins, Cookie, ExternalLink, EyeOff, FileText, Filter, Flame, Gauge, Globe, ImageUp, Keyboard, Languages, Layers, LayoutDashboard, Link2, Lock, LogIn, Mail, MousePointerClick, Palette, Play, Radio, Repeat, Route, ScrollText, Search, Smartphone, Sparkles, StickyNote, Target, Trophy, Upload, Users, Zap, type LucideIcon } from 'lucide-react'

export const ICONS: Record<string, LucideIcon> = {
  live: Radio,
  allsites: LayoutDashboard,
  map: Globe,
  ai: Sparkles,
  crawlers: Bot,
  search: Search,
  outbound: ExternalLink,
  forms: ClipboardList,
  rhythm: Clock,
  goals: Target,
  funnels: Filter,
  journeys: Route,
  retention: Repeat,
  vitals: Gauge,
  heatmaps: Flame,
  notes: StickyNote,
  milestones: Trophy,
  replay: Play,
  segments: Layers,
  surge: Zap,
  revenue: Coins,
  sales: Banknote,
  sharelinks: Link2,
  sharecard: ImageUp,
  whitelabel: Palette,
  reports: FileText,
  weekly: Mail,
  widgets: MousePointerClick,
  people: Users,
  keys: Code,
  sso: LogIn,
  twostep: Lock,
  privacy: ScrollText,
  consent: Cookie,
  exclude: EyeOff,
  bots: Ban,
  install: Code,
  ga: Upload,
  pwa: Smartphone,
  language: Languages,
  shortcuts: Keyboard,
  peek: Bot,
  modules: Gauge,
  health: Activity,
}
