// The name and the one short line of every feature in the Features pop-up.
import { defineCopy } from '../../i18n'

export const words = defineCopy('featureList', {
  live: { name: 'Live view', line: 'Who is on your site right now' },
  calendar: { name: 'Calendar', line: 'Your month, day by day' },
  allsites: { name: 'All sites', line: 'Every site on one page' },
  map: { name: 'Map', line: 'Visitors on a world map' },
  ai: { name: 'AI & Search', line: 'Google, AI assistants and crawlers' },
  crawlers: { name: 'AI crawlers', line: 'Which robots read your pages' },
  search: { name: 'Search Console', line: 'The searches that found you' },
  outbound: { name: 'Outbound links', line: 'Clicks that leave, and downloads' },
  forms: { name: 'Form submissions', line: 'Every form sent, counted' },
  rhythm: { name: 'Weekly rhythm', line: 'When people come, by hour' },
  goals: { name: 'Goals', line: 'Count signups and more' },
  funnels: { name: 'Funnels', line: 'Where visitors stop' },
  journeys: { name: 'Journeys', line: 'One visitor’s whole history' },
  retention: { name: 'Retention', line: 'Who comes back' },
  vitals: { name: 'Web Vitals', line: 'How fast pages feel' },
  heatmaps: { name: 'Heatmaps', line: 'Where people click and stop' },
  notes: { name: 'Notes', line: 'Mark a day on the chart' },
  milestones: { name: 'Milestones', line: 'Round numbers, celebrated' },
  replay: { name: 'Replay', line: 'Your period, played as a story' },
  segments: { name: 'Segments', line: 'Filters you save and reuse' },
  surge: { name: 'Surge alerts', line: 'A message when traffic jumps' },
  revenue: { name: 'Revenue', line: 'Which traffic pays' },
  sales: { name: 'Sale notices', line: 'A chime and a notice per sale' },
  sharelinks: { name: 'Share links', line: 'Read-only, with a password if you like' },
  sharecard: { name: 'Share cards', line: 'A picture of your numbers' },
  whitelabel: { name: 'White-label', line: 'Your colour and logo on shared pages' },
  reports: { name: 'Client reports', line: 'The numbers by email, on a schedule' },
  weekly: { name: 'Weekly email', line: 'Last week, in your inbox' },
  widgets: { name: 'Widgets', line: 'Badges and counters for your pages' },
  people: { name: 'People', line: 'Invite owners and viewers' },
  keys: { name: 'API keys', line: 'For scripts and assistants' },
  sso: { name: 'Single sign-on', line: 'Google, Microsoft or OpenID Connect' },
  twostep: { name: 'Two-step sign-in', line: 'A code from your authenticator' },
  privacy: { name: 'Privacy report', line: 'What you collect, on one page' },
  consent: { name: 'Cookie consent', line: 'Ask first, or read your banner' },
  exclude: { name: 'Exclude my visits', line: 'Your own clicks, left out' },
  bots: { name: 'Bot filtering', line: 'Robots and data centres, left out' },
  install: { name: 'Install', line: 'The snippet, and a check it works' },
  ga: { name: 'Google Analytics import', line: 'Bring your history along' },
  pwa: { name: 'Install the app', line: 'On your home screen' },
  language: { name: 'Languages', line: 'English, German, French, Spanish, Italian, Dutch' },
  shortcuts: { name: 'Shortcuts', line: 'Keys for the things you do most' },
  peek: { name: 'Peek', line: 'Ask your own assistant, over MCP' },
  modules: { name: 'Modules', line: 'Switch pieces on, see their weight' },
  health: { name: 'Health', line: 'How this server is doing' },
})
